server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourEmailId
    password: yourPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
